baseURL = 'https://deltamaniac.github.io/'
languageCode = 'en-us'
title = 'AERIS '

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]

[[menu.main]]
name = "Home"
pre = "<span data-feather='home'></span>"
url = "/"
weight = 1

[[menu.main]]
identifier = "posts"

url = "/posts/"

pre = ""

post = ""

# Display name
name = "Posts"

# Weights are used to determine the ordering
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2


[[menu.main]]
identifier = "about"
name = "About"
pre = "<span data-feather='user'></span>"
url = "/about"
weight = 3

[[menu.main]]
identifier = "github"
url = "https://github.com/deltamaniac"
pre = "<span data-feather='github'></span>"
weight = 4

[[menu.main]]
identifier = "rss"
pre = "<span data-feather='rss'></span>"
url = "/index.xml"
weight = 5


[params]
# URL for the avatar on homepage
avatarURL = "/images/home/home.png"

# Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
avatarSize = "size-xl"

# Description to display on homepage
description = "This is a tactical retreat in the face of overwhelming boredom – Argel Tal"

# Accent color is displayed when you hover over <a> tags
accentColor = "#FF4D4D"

# Display "back to top" button on posts and pages
ShowBackToTopButton = true

# You can use this to inject any HTML in the <head> tag.
# Ideal usecase for this is to import custom js/css or add your analytics snippet
customHeadHTML = ""

# Keywords relevant for SEO
metaKeywords = ["blog", "gokarna", "hugo"]

# If you want to display posts on the homepage, the options are
# "popular" (order posts by weight), "recent" (order posts by date)
# or "" (do not display, default option)
showPostsOnHomePage = "recent"

# Defines number of posts displayed on homepage if showPostsOnHomePage option is set
# Default value is 4
numberPostsOnHomePage = 4

# Footer text
footer = "DeltaManiac"

togglePreviousAndNextButtons = "true"
