# uncomment to preview locally
#theme: "just-the-docs"
remote_theme: dendronhq/dendron-jekyll
title: BrainMatter
logo: "/assets/images/logo.png"
exclude: [ "node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile", "*/dendron.template.release.md"
]
footer_content: ""

gh_edit_link: true

# seo
tagline: "All the stuff supposed to be in my Brain"
description: "Thoughts, Stuff to do, Stuff to remember, Everything goes here"
twitter:
  card: summary
  username: delta_maniac
author:
  twitter: delta_maniac

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      image: "/assets/images/logo.png"
